apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - ../5-demo-source-git-bb-app.yaml
  - ../5-demo-helm-release-git-helm-bb-app.yml

